### ISSUE TITLE
compilation error 

### ISSUE THREAD

**Issue by mowrang** [h2so5/mruby-tinyxml2#1]
I am getting the below error at line 799 and 952 

error: invalid static_cast from type ‘const char*’ to type ‘char*’

**Comment by mowrang** [comment]
Below is the complete error message: 

/xml_test/mruby-tinyxml2-master/src/mruby-tinyxml2.cpp: In function ‘mrb_value xml_element_set_attribute(mrb_state*, mrb_value)’:
/xml_test/mruby-tinyxml2-master/src/mruby-tinyxml2.cpp:799:86: error: invalid static_cast from type ‘const char*’ to type ‘char*’
     element->SetAttribute(name, static_cast<char*>(mrb_string_value_cstr(mrb, &value)));
                                                                                      ^
/xml_test/mruby-tinyxml2-master/src/mruby-tinyxml2.cpp: In function ‘mrb_value xml_attribute_set_attribute(mrb_state*, mrb_value)’:
/xml_test/mruby-tinyxml2-master/src/mruby-tinyxml2.cpp:952:82: error: invalid static_cast from type ‘const char*’ to type ‘char*’
     attribute->SetAttribute(static_cast<char*>(mrb_string_value_cstr(mrb, &value)));
                                                                                  ^
/xml_test/mruby-tinyxml2-master/src/mruby-tinyxml2.cpp: In function ‘mrb_value xml_element_set_attribute(mrb_state*, mrb_value)’:
/xml_test/mruby-tinyxml2-master/src/mruby-tinyxml2.cpp:799:86: error: invalid static_cast from type ‘const char*’ to type ‘char*’
     element->SetAttribute(name, static_cast<char*>(mrb_string_value_cstr(mrb, &value)));
                                                                                      ^
/xml_test/mruby-tinyxml2-master/src/mruby-tinyxml2.cpp: In function ‘mrb_value xml_attribute_set_attribute(mrb_state*, mrb_value)’:
/xml_test/mruby-tinyxml2-master/src/mruby-tinyxml2.cpp:952:82: error: invalid static_cast from type ‘const char*’ to type ‘char*’
     attribute->SetAttribute(static_cast<char*>(mrb_string_value_cstr(mrb, &value)));
                                                                                  ^
rake aborted!

**Comment by h2so5** [comment]
@mowrang Thanks :smiley_cat:
