### ISSUE TITLE
Unable to compile mruby app with TinyXML2

### ISSUE THREAD

**Issue by sci-phi** [h2so5/mruby-tinyxml2#5]
I have written an mruby app which uses TinyXML2, and I want to package it into an executable, per the docs ("http://mruby.org/docs/articles/executing-ruby-code-with-mruby.html") but I am unable to compile the mruby app with TinyXML usage, even though it runs fine when executed via mruby.

/usr/src/repo/mruby/build/host/lib/libmruby.a(vm.cxx.o): In function `mrb_funcall_with_block':
/usr/src/repo/mruby/src/vm.c:401: undefined reference to `__cxa_begin_catch'
/usr/src/repo/mruby/src/vm.c:401: undefined reference to `__cxa_allocate_exception'
/usr/src/repo/mruby/src/vm.c:401: undefined reference to `typeinfo for long'
/usr/src/repo/mruby/src/vm.c:401: undefined reference to `__cxa_throw'
/usr/src/repo/mruby/src/vm.c:401: undefined reference to `__cxa_end_catch'
/usr/src/repo/mruby/src/vm.c:401: undefined reference to `__cxa_end_catch'
/usr/src/repo/mruby/build/host/lib/libmruby.a(vm.cxx.o): In function `mrb_vm_exec':
/usr/src/repo/mruby/src/vm.c:1895: undefined reference to `__cxa_allocate_exception'
/usr/src/repo/mruby/src/vm.c:1895: undefined reference to `typeinfo for long'
/usr/src/repo/mruby/src/vm.c:1895: undefined reference to `__cxa_throw'
/usr/src/repo/mruby/src/vm.c:2043: undefined reference to `__cxa_allocate_exception'
/usr/src/repo/mruby/src/vm.c:2043: undefined reference to `typeinfo for long'
/usr/src/repo/mruby/src/vm.c:2043: undefined reference to `__cxa_throw'
/usr/src/repo/mruby/src/vm.c:2946: undefined reference to `__cxa_begin_catch'
/usr/src/repo/mruby/src/vm.c:2946: undefined reference to `__cxa_allocate_exception'
/usr/src/repo/mruby/src/vm.c:2946: undefined reference to `typeinfo for long'
/usr/src/repo/mruby/src/vm.c:2946: undefined reference to `__cxa_throw'
/usr/src/repo/mruby/src/vm.c:2946: undefined reference to `__cxa_end_catch'
/usr/src/repo/mruby/src/vm.c:2946: undefined reference to `__cxa_end_catch'
/usr/src/repo/mruby/build/host/lib/libmruby.a(vm.cxx.o):(.data.DW.ref._ZTIl[DW.ref._ZTIl]+0x0): undefined reference to `typeinfo for long'
/usr/src/repo/mruby/build/host/lib/libmruby.a(vm.cxx.o):(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'
/usr/src/repo/mruby/build/host/lib/libmruby.a(error.cxx.o): In function `mrb_exc_raise':
/usr/src/repo/mruby/src/error.c:253: undefined reference to `__cxa_allocate_exception'
/usr/src/repo/mruby/src/error.c:253: undefined reference to `typeinfo for long'
/usr/src/repo/mruby/src/error.c:253: undefined reference to `__cxa_throw'
/usr/src/repo/mruby/build/host/lib/libmruby.a(mruby-tinyxml2.o): In function `xml_document_initialize(mrb_state*, mrb_value)':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/mruby-tinyxml2.cpp:442: undefined reference to `operator new(unsigned long)'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/mruby-tinyxml2.cpp:442: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(mruby-tinyxml2.o): In function `tinyxml2::XMLVisitor::~XMLVisitor()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:414: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(mruby-tinyxml2.o): In function `tinyxml2::XMLPrinter::~XMLPrinter()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:1871: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(mruby-tinyxml2.o): In function `tinyxml2::DynArray<char const*, 10>::~DynArray()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:199: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(mruby-tinyxml2.o): In function `tinyxml2::DynArray<char, 20>::~DynArray()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:199: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(mruby-tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml210XMLVisitorE[_ZTIN8tinyxml210XMLVisitorE]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(exception.cxx.o): In function `mrb_protect':
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:18: undefined reference to `__cxa_begin_catch'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:18: undefined reference to `__cxa_allocate_exception'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:18: undefined reference to `typeinfo for long'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:18: undefined reference to `__cxa_throw'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:18: undefined reference to `__cxa_end_catch'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:18: undefined reference to `__cxa_end_catch'
/usr/src/repo/mruby/build/host/lib/libmruby.a(exception.cxx.o): In function `mrb_ensure':
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:40: undefined reference to `__cxa_begin_catch'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:40: undefined reference to `__cxa_allocate_exception'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:40: undefined reference to `typeinfo for long'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:40: undefined reference to `__cxa_throw'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:43: undefined reference to `__cxa_allocate_exception'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:43: undefined reference to `typeinfo for long'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:43: undefined reference to `__cxa_throw'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:40: undefined reference to `__cxa_end_catch'
/usr/src/repo/mruby/build/host/lib/libmruby.a(exception.cxx.o): In function `mrb_rescue_exceptions':
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:72: undefined reference to `__cxa_begin_catch'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:72: undefined reference to `__cxa_allocate_exception'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:72: undefined reference to `typeinfo for long'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:72: undefined reference to `__cxa_throw'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:82: undefined reference to `__cxa_allocate_exception'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:82: undefined reference to `typeinfo for long'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:82: undefined reference to `__cxa_throw'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:72: undefined reference to `__cxa_end_catch'
/usr/src/repo/mruby/mrbgems/mruby-error/src/exception.c:72: undefined reference to `__cxa_end_catch'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::StrPair::Reset()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:92: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::StrPair::SetStr(char const*, int)':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:104: undefined reference to `operator new[](unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLNode::~XMLNode()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:596: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLComment::~XMLComment()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:912: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLDeclaration::~XMLDeclaration()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:959: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLUnknown::~XMLUnknown()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:1005: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLElement::~XMLElement()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:1181: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLDocument::~XMLDocument()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:1504: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLDocument::~XMLDocument()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:1521: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLDocument::Clear()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:1532: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLDocument::LoadFile(_IO_FILE*)':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:1616: undefined reference to `operator new[](unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLDocument::Parse(char const*, unsigned long)':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.cpp:1677: undefined reference to `operator new[](unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::MemPool::~MemPool()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:283: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLText::~XMLText()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:852: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::XMLAttribute::~XMLAttribute()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:1073: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::MemPoolT<88>::Alloc()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:317: undefined reference to `operator new(unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::MemPoolT<96>::Alloc()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:317: undefined reference to `operator new(unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::MemPoolT<104>::Alloc()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:317: undefined reference to `operator new(unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::MemPoolT<72>::Alloc()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:317: undefined reference to `operator new(unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::MemPoolT<104>::~MemPoolT()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:303: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::MemPoolT<104>::~MemPoolT()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:305: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::MemPoolT<72>::~MemPoolT()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:303: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::MemPoolT<72>::~MemPoolT()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:305: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::MemPoolT<96>::~MemPoolT()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:303: undefined reference to `operator delete(void*, unsigned long)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:305: more undefined references to `operator delete(void*, unsigned long)' follow
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::DynArray<tinyxml2::MemPoolT<104>::Block*, 10>::~DynArray()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:199: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::DynArray<tinyxml2::MemPoolT<72>::Block*, 10>::~DynArray()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:199: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::DynArray<tinyxml2::MemPoolT<96>::Block*, 10>::~DynArray()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:199: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::DynArray<tinyxml2::MemPoolT<88>::Block*, 10>::~DynArray()':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:199: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::DynArray<char, 20>::EnsureCapacity(int)':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:258: undefined reference to `operator new[](unsigned long)'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:261: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::DynArray<char const*, 10>::EnsureCapacity(int)':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:258: undefined reference to `operator new[](unsigned long)'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:258: undefined reference to `__cxa_throw_bad_array_new_length'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:261: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::DynArray<tinyxml2::MemPoolT<88>::Block*, 10>::EnsureCapacity(int)':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:258: undefined reference to `operator new[](unsigned long)'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:258: undefined reference to `__cxa_throw_bad_array_new_length'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:261: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::DynArray<tinyxml2::MemPoolT<96>::Block*, 10>::EnsureCapacity(int)':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:258: undefined reference to `operator new[](unsigned long)'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:258: undefined reference to `__cxa_throw_bad_array_new_length'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:261: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::DynArray<tinyxml2::MemPoolT<104>::Block*, 10>::EnsureCapacity(int)':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:258: undefined reference to `operator new[](unsigned long)'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:258: undefined reference to `__cxa_throw_bad_array_new_length'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:261: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o): In function `tinyxml2::DynArray<tinyxml2::MemPoolT<72>::Block*, 10>::EnsureCapacity(int)':
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:258: undefined reference to `operator new[](unsigned long)'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:258: undefined reference to `__cxa_throw_bad_array_new_length'
/usr/src/repo/mruby/build/mrbgems/mruby-tinyxml2/src/tinyxml2.h:261: undefined reference to `operator delete[](void*)'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTVN8tinyxml27XMLNodeE[_ZTVN8tinyxml27XMLNodeE]+0x70): undefined reference to `__cxa_pure_virtual'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTVN8tinyxml27XMLNodeE[_ZTVN8tinyxml27XMLNodeE]+0x78): undefined reference to `__cxa_pure_virtual'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTVN8tinyxml27XMLNodeE[_ZTVN8tinyxml27XMLNodeE]+0x80): undefined reference to `__cxa_pure_virtual'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTVN8tinyxml27MemPoolE[_ZTVN8tinyxml27MemPoolE]+0x20): undefined reference to `__cxa_pure_virtual'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTVN8tinyxml27MemPoolE[_ZTVN8tinyxml27MemPoolE]+0x28): undefined reference to `__cxa_pure_virtual'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTVN8tinyxml27MemPoolE[_ZTVN8tinyxml27MemPoolE]+0x30): more undefined references to `__cxa_pure_virtual' follow
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml210XMLPrinterE[_ZTIN8tinyxml210XMLPrinterE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml211XMLDocumentE[_ZTIN8tinyxml211XMLDocumentE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml28MemPoolTILi88EEE[_ZTIN8tinyxml28MemPoolTILi88EEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml28MemPoolTILi96EEE[_ZTIN8tinyxml28MemPoolTILi96EEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml28MemPoolTILi72EEE[_ZTIN8tinyxml28MemPoolTILi72EEE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml28MemPoolTILi104EEE[_ZTIN8tinyxml28MemPoolTILi104EEE]+0x0): more undefined references to `vtable for __cxxabiv1::__si_class_type_info' follow
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml212XMLAttributeE[_ZTIN8tinyxml212XMLAttributeE]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml210XMLUnknownE[_ZTIN8tinyxml210XMLUnknownE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml214XMLDeclarationE[_ZTIN8tinyxml214XMLDeclarationE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml210XMLCommentE[_ZTIN8tinyxml210XMLCommentE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml27XMLTextE[_ZTIN8tinyxml27XMLTextE]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml27XMLNodeE[_ZTIN8tinyxml27XMLNodeE]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'
/usr/src/repo/mruby/build/host/lib/libmruby.a(tinyxml2.o):(.data.rel.ro._ZTIN8tinyxml27MemPoolE[_ZTIN8tinyxml27MemPoolE]+0x0): undefined reference to `vtable for __cxxabiv1::__class_type_info'

**Comment by h2so5** [comment]
TinyXML2 depends on the C++ standard library.
Try using `-lstdc++` option.

**Comment by sci-phi** [comment]
Thanks, that worked!
